CREATE DATABASE IF NOT EXISTS api;
CREATE DATABASE IF NOT EXISTS worker;

CREATE USER IF NOT EXISTS 'api_user'@'%' IDENTIFIED BY 'api_pass';
GRANT SELECT, INSERT, UPDATE, CREATE, ALTER, INDEX ON api.* TO 'api_user'@'%';

CREATE USER IF NOT EXISTS 'worker_user'@'%' IDENTIFIED BY 'worker_pass';
GRANT SELECT, INSERT, CREATE, ALTER, INDEX ON worker.* TO 'worker_user'@'%';

FLUSH PRIVILEGES;
